version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    command: node server.js

  client:
    build: ./client
    ports:
      - "3002:3002"
    command: node server.js
